# Based on the workflows of:
# https://github.com/League-of-Foundry-Developers/FoundryVTT-Module-Template and
# https://github.com/pwatson100/alienrpg
name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      # run the npm command 'npm run pack-compendiums' to create the compendium packs before creating the release, so I need to set up node first
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25' # Specify the Node.js version you want to use
      - name: Install Dependencies
        run: npm install
        
      # run 'pack-compendiums' in from package.json to create the compendium packs before creating the release
      - name: Pack Compendiums
        run: npm run pack-compendium

      # Substitute the Manifest and Download URLs in the system.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: "system.json"
        env:
          version: ${{github.event.release.tag_name}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/system.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip

      # Create a zip file with all files required by the system to add to the release
      - run: zip -r ./system.zip CHANGELOG.md LICENSE.txt README.md system.json package.json package-lock.json template.json version.txt assets/ css/ fonts/ lang/ lib/ module/ packs/ src/ templates/

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # Set this to false if you want to prevent updating existing releases
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./system.json, ./system.zip"
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}
      - name: Publish Module to FoundryVTT Website
        id: publish-to-foundry-website
        uses: cs96and/FoundryVTT-release-package@v1
        with:
          package-token: ${{ secrets.PACKAGE_TOKEN }}
          manifest-url: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.json
